name: Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Install dependencies
        working-directory: ./websocket-service
        run: npm ci

      - name: Build
        working-directory: ./websocket-service
        run: npm run build
        
      - name: Run linter
        working-directory: ./websocket-service
        run: npm run lint